package render

import (
	"fmt"
	"image"
	"time"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/trancecode/vantage/geometry"
)

// UsePlaceholderSpriteImages, when true, makes Sprite.Image return a placeholder
// for a missing animation type instead of panicking. Set by engine configuration.
var UsePlaceholderSpriteImages bool

// Sprite represents a game sprite with animations.
type Sprite struct {
	Animations   map[AnimationType]*Animation
	ZeroPosition geometry.Vector2
	Scale        float64
	Type         SpriteType

	// SourceTileSize is the tile size this sprite's art was drawn for. Zero
	// means it was drawn for whatever the game's tile size is, so no correction
	// applies. It is authorial metadata and is never inferred from the image: a
	// 64 pixel image drawn for 128 pixel tiles and a 64 pixel image drawn for 32
	// pixel tiles are different sprites that happen to share a file size.
	SourceTileSize float64

	// cachedVisibleTopAboveZero caches the result of VisibleTopAboveZero.
	cachedVisibleTopAboveZero *float64

	// cachedVisibleBounds caches the result of VisibleBounds.
	cachedVisibleBounds *image.Rectangle
}

// Animation represents a sequence of images forming an animation.
type Animation struct {
	Images   []*ebiten.Image
	Duration time.Duration
}

// NewSprite creates and returns a new Sprite with default values.
func NewSprite() *Sprite {
	return &Sprite{
		Animations:   make(map[AnimationType]*Animation),
		ZeroPosition: geometry.Zero2D(),
		Scale:        1.0,
	}
}

// AddImage adds an image to the specified animation type.
func (s *Sprite) AddImage(animationType AnimationType, img *ebiten.Image) {
	if _, ok := s.Animations[animationType]; !ok {
		s.Animations[animationType] = &Animation{
			Images: []*ebiten.Image{},
		}
	}
	s.Animations[animationType].Images = append(s.Animations[animationType].Images, img)
}

// Image returns the first image of the specified animation type.
// It panics if the animation type does not exist or has no images, unless
// UsePlaceholderSpriteImages is set, in which case it returns nil.
func (s *Sprite) Image(animationType AnimationType) *ebiten.Image {
	if _, ok := s.Animations[animationType]; !ok || len(s.Animations[animationType].Images) == 0 {
		if !UsePlaceholderSpriteImages {
			panic(fmt.Sprintf("no such animation type: %s", animationType))
		}
		// TODO: return a default image
		return nil
	}
	return s.Animations[animationType].Images[0]
}

// HasAnimation checks if the sprite has a specific animation defined.
func (s *Sprite) HasAnimation(a AnimationType) bool {
	_, ok := s.Animations[a]
	return ok
}

// CanAnimate checks if the sprite can perform a specific animation, either directly or by flipping an existing animation.
func (s *Sprite) CanAnimate(a AnimationType) bool {
	if s.HasAnimation(a) {
		return true
	}
	other, canGenerate := MirroredAnimations[a]
	return canGenerate && s.HasAnimation(other)
}

// AllAnimations returns a slice of all animation types the sprite can draw.
func (s *Sprite) AllAnimations() []AnimationType {
	animations := make([]AnimationType, 0)
	for a := range s.Animations {
		animations = append(animations, a)
	}
	// Add animations that can be generated by flipping (and are not already present)
	for a, other := range MirroredAnimations {
		if !s.HasAnimation(a) && s.HasAnimation(other) {
			animations = append(animations, a)
		}
	}
	return animations
}

// Draw draws the sprite at the given position with the specified animation type.
func (s *Sprite) Draw(screen *ebiten.Image, c *Camera, p geometry.Vector2, a AnimationType) {
	var img *ebiten.Image
	requiresFlip := false

	// A missing animation can be rendered by horizontally flipping its mirror.
	if _, ok := s.Animations[a]; !ok {
		if existingAnimationType, shouldFlip := MirroredAnimations[a]; shouldFlip {
			img = s.Image(existingAnimationType)
			if _, ok := s.Animations[existingAnimationType]; ok {
				requiresFlip = true
			}
		}
	}

	if img == nil {
		img = s.Image(a)
	}
	if img == nil {
		return
	}

	op := s.buildDrawOp(p, requiresFlip, c, 1.0)
	screen.DrawImage(img, op)
}

// buildDrawOp builds the draw options for the sprite at world-tile position p:
// sprite scale combined with the tile ratio and displayScale, zero-position
// offset, optional horizontal flip, then the camera transform.
//
// displayScale multiplies s.Scale instead of replacing it, and the
// zero-position offset is multiplied by it as well. Because that offset is
// applied in post-scale space, scaling both by the same factor makes
// displayScale a uniform shrink about the zero position: the pixel anchored at
// the world position p stays at p, and only the drawn extent changes. A
// displayScale of 1 reproduces the unscaled transform exactly.
func (s *Sprite) buildDrawOp(p geometry.Vector2, requiresFlip bool, c *Camera, displayScale float64) *ebiten.DrawImageOptions {
	op := &ebiten.DrawImageOptions{}
	op.Filter = SpriteFilter
	// The tile ratio is an engine-applied uniform scale about the anchor, so it
	// multiplies in exactly where displayScale does. ZeroPosition keeps its
	// existing meaning, in Scale-applied pixels, which is why the translate does
	// not include Scale.
	ratio := s.tileRatio()
	scale := s.Scale * ratio * displayScale
	op.GeoM.Scale(scale, scale)
	anchor := ratio * displayScale
	op.GeoM.Translate(-s.ZeroPosition.X()*anchor, -s.ZeroPosition.Y()*anchor)
	if requiresFlip {
		op.GeoM.Scale(-1, 1)
	}
	c.Adjust(op, p)
	return op
}

// DrawAnimation draws the sprite at the given position with the specified animation type.
func (s *Sprite) DrawAnimation(screen *ebiten.Image, c *Camera, p geometry.Vector2, a AnimationType, duration time.Duration) {
	s.DrawAnimationScaled(screen, c, p, a, duration, 1.0)
}

// DrawAnimationScaled is DrawAnimation with an extra per-draw display scale,
// for views that need a sprite drawn smaller or larger than the game draws it
// without mutating the sprite. displayScale multiplies Sprite.Scale for this
// call only; SetScale would change the sprite everywhere it is drawn, since a
// sprite library hands out the same pointer to every caller.
//
// The scale is uniform about the sprite's zero position, so the anchor point
// stays on p at any display scale and only the drawn extent changes. A
// displayScale of 1 is identical to DrawAnimation.
func (s *Sprite) DrawAnimationScaled(screen *ebiten.Image, c *Camera, p geometry.Vector2, a AnimationType, duration time.Duration, displayScale float64) {
	var requiresFlip bool
	animation, animationExists := s.Animations[a]

	if !animationExists {
		// Check if we need to flip horizontally
		if existingAnimationType, shouldFlip := MirroredAnimations[a]; shouldFlip {
			requiresFlip = true
			animation = s.Animations[existingAnimationType]
		} else {
			panic(fmt.Sprintf("no such animation type: %s", a))
		}
	}

	if len(animation.Images) == 0 {
		panic(fmt.Sprintf("no image for this animation type: %s", a))
	}

	// Determine which frame to draw based on the duration and animation speed
	frameIndex := 0
	if animation.Duration > 0 {
		frameIndex = int(duration / (animation.Duration / time.Duration(len(animation.Images))))
		frameIndex %= len(animation.Images) // Loop the animation
	}

	img := animation.Images[frameIndex]
	if img == nil {
		return
	}

	op := s.buildDrawOp(p, requiresFlip, c, displayScale)
	screen.DrawImage(img, op)
}

// VisibleBounds returns the bounding rectangle of non-transparent pixels in
// one frame, expressed in frame-local pixel coordinates. Cached after first
// call. Returns an empty rectangle if no visible content is found.
func (s *Sprite) VisibleBounds() image.Rectangle {
	if s.cachedVisibleBounds != nil {
		return *s.cachedVisibleBounds
	}
	var img *ebiten.Image
	for _, anim := range s.Animations {
		if len(anim.Images) > 0 {
			img = anim.Images[0]
			break
		}
	}
	var result image.Rectangle
	if img != nil {
		frame := img.Bounds()
		minX, minY := frame.Max.X, frame.Max.Y
		maxX, maxY := frame.Min.X-1, frame.Min.Y-1
		for y := frame.Min.Y; y < frame.Max.Y; y++ {
			for x := frame.Min.X; x < frame.Max.X; x++ {
				_, _, _, a := img.At(x, y).RGBA()
				if a == 0 {
					continue
				}
				if x < minX {
					minX = x
				}
				if x > maxX {
					maxX = x
				}
				if y < minY {
					minY = y
				}
				if y > maxY {
					maxY = y
				}
			}
		}
		if maxX >= minX && maxY >= minY {
			// Normalize to frame-local (0,0) origin.
			result = image.Rect(
				minX-frame.Min.X, minY-frame.Min.Y,
				maxX-frame.Min.X+1, maxY-frame.Min.Y+1,
			)
		}
	}
	s.cachedVisibleBounds = &result
	return result
}

// VisibleTopAboveZero returns how far the visible sprite content
// (non-transparent pixels) extends above ZeroPosition in one frame, measured in
// drawn pixels including the tile ratio: the frame is scaled by Scale before
// the zero-position offset is applied (see buildDrawOp), so the row offset is
// multiplied by Scale to match what ends up on screen. Frames across
// animations share the same size and layout, so the result is computed once
// from any available frame and cached; the cache holds the pre-ratio value, so
// the ratio is applied fresh on every call and a tile size changed after the
// first call still takes effect.
//
// Use this instead of the raw frame height when placing UI elements (like
// nameplates) above a sprite: transparent padding at the top of the frame is
// not counted, and the result maps to screen pixels by a single multiply with
// the camera's effective zoom.
//
// The result describes a draw at a display scale of 1, which is what
// DrawAnimation uses. DrawAnimationScaled scales uniformly about the zero
// position, so a caller placing UI above a sprite drawn at a display scale
// multiplies this result by that same scale.
func (s *Sprite) VisibleTopAboveZero() float64 {
	if s.cachedVisibleTopAboveZero != nil {
		return *s.cachedVisibleTopAboveZero * s.tileRatio()
	}

	var img *ebiten.Image
	for _, anim := range s.Animations {
		if len(anim.Images) > 0 {
			img = anim.Images[0]
			break
		}
	}
	result := 0.0
	if img != nil {
		bounds := img.Bounds()
		for y := bounds.Min.Y; y < bounds.Max.Y; y++ {
			rowHasPixel := false
			for x := bounds.Min.X; x < bounds.Max.X; x++ {
				_, _, _, a := img.At(x, y).RGBA()
				if a > 0 {
					rowHasPixel = true
					break
				}
			}
			if rowHasPixel {
				// (y - bounds.Min.Y) is the row index within the frame. The
				// frame is drawn scaled by Scale, so the first visible pixel
				// sits ZeroPosition.Y() - rowIndex*Scale drawn pixels above
				// ZeroPosition.
				result = s.ZeroPosition.Y() - float64(y-bounds.Min.Y)*s.Scale
				break
			}
		}
	}

	s.cachedVisibleTopAboveZero = &result
	return result * s.tileRatio()
}

// SetScale sets the scale of the sprite.
func (s *Sprite) SetScale(scale float64) *Sprite {
	s.Scale = scale
	return s
}

// SetSourceTileSize sets the tile size this sprite's art was drawn for and
// returns the sprite, so it chains with the other setters.
func (s *Sprite) SetSourceTileSize(size float64) *Sprite {
	s.SourceTileSize = size
	return s
}

// tileRatio is the scale that maps art drawn for SourceTileSize onto the game's
// current TileSize. It is computed on every call rather than stored, because
// sprites are built from init() before settings are applied.
func (s *Sprite) tileRatio() float64 {
	if s.SourceTileSize <= 0 {
		return 1.0
	}
	return TileSize / s.SourceTileSize
}

// SetZeroPosition sets the zero position of the sprite.
func (s *Sprite) SetZeroPosition(pos geometry.Vector2) *Sprite {
	s.ZeroPosition = pos
	return s
}

// SetType sets the type of the sprite.
func (s *Sprite) SetType(spriteType SpriteType) *Sprite {
	s.Type = spriteType
	return s
}

// MirroredAnimations maps a left-facing animation to the right-facing animation
// it is rendered from by a horizontal flip, so left variants need not be
// authored separately.
var (
	MirroredAnimations = map[AnimationType]AnimationType{
		AnimationIdleLeft:   AnimationIdleRight,
		AnimationMoveLeft:   AnimationMoveRight,
		AnimationAttackLeft: AnimationAttackRight,
	}
)

// LoadSprite slices img into a grid of width columns by height rows, assigns the frame indexes in indexes to each
// AnimationType, and sets per-animation durations (defaulting to one second when unspecified). Note: width and height
// are column/row counts, not pixel dimensions.
func LoadSprite(img *ebiten.Image, width, height int, indexes map[AnimationType][]int, durations map[AnimationType]time.Duration) (*Sprite, error) {
	sprite := NewSprite()
	// Get the size of each tile
	w, h := img.Bounds().Dx(), img.Bounds().Dy()
	tileWidth := w / width
	tileHeight := h / height

	for animationType, animationIndexes := range indexes {
		for _, index := range animationIndexes {
			// Calculate the position of the tile in the sprite sheet
			x := (index % width) * tileWidth
			y := (index / width) * tileHeight

			// Create a sub-image of the tile
			rect := image.Rect(x, y, x+tileWidth, y+tileHeight)
			subImg := img.SubImage(rect).(*ebiten.Image)

			// Add the tile to the animation
			sprite.AddImage(animationType, subImg)
		}

		// Set the animation duration if it exists. An empty index list means no
		// animation entry was created above, so there is nothing to set.
		duration, ok := durations[animationType]
		if !ok {
			duration = time.Second
		}
		if animation, ok := sprite.Animations[animationType]; ok {
			animation.Duration = duration
		}
	}

	return sprite, nil
}

// MustLoadSprite is like LoadSprite but panics on error.
func MustLoadSprite(img *ebiten.Image, width, height int, indexes map[AnimationType][]int, durations map[AnimationType]time.Duration) *Sprite {
	sprite, err := LoadSprite(img, width, height, indexes, durations)
	if err != nil {
		panic(fmt.Sprintf("loading sprite: %v", err))
	}
	return sprite
}
