// Code generated by "stringer -type=AnimationType -output=render_animation_string.go"; DO NOT EDIT.

package render

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AnimationDefault-0]
	_ = x[AnimationMoveUp-1]
	_ = x[AnimationMoveDown-2]
	_ = x[AnimationMoveLeft-3]
	_ = x[AnimationMoveRight-4]
	_ = x[AnimationIdleUp-5]
	_ = x[AnimationIdleDown-6]
	_ = x[AnimationIdleLeft-7]
	_ = x[AnimationIdleRight-8]
	_ = x[AnimationAttackUp-9]
	_ = x[AnimationAttackDown-10]
	_ = x[AnimationAttackLeft-11]
	_ = x[AnimationAttackRight-12]
}

const _AnimationType_name = "AnimationDefaultAnimationMoveUpAnimationMoveDownAnimationMoveLeftAnimationMoveRightAnimationIdleUpAnimationIdleDownAnimationIdleLeftAnimationIdleRightAnimationAttackUpAnimationAttackDownAnimationAttackLeftAnimationAttackRight"

var _AnimationType_index = [...]uint8{0, 16, 31, 48, 65, 83, 98, 115, 132, 150, 167, 186, 205, 225}

func (i AnimationType) String() string {
	if i < 0 || i >= AnimationType(len(_AnimationType_index)-1) {
		return "AnimationType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AnimationType_name[_AnimationType_index[i]:_AnimationType_index[i+1]]
}
