// Code generated by "stringer -type=SpriteType -output=render_spritetype_string.go"; DO NOT EDIT.

package render

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SpriteTypeUnknown-0]
	_ = x[SpriteTypeActor-1]
	_ = x[SpriteTypeTerrain-2]
}

const _SpriteType_name = "SpriteTypeUnknownSpriteTypeActorSpriteTypeTerrain"

var _SpriteType_index = [...]uint8{0, 17, 32, 49}

func (i SpriteType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_SpriteType_index)-1 {
		return "SpriteType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SpriteType_name[_SpriteType_index[idx]:_SpriteType_index[idx+1]]
}
