package render

import (
	"fmt"
	"image"
	"slices"
	"time"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/trancecode/vantage/geometry"
)

// UsePlaceholderSpriteImages, when true, makes Sprite.Image return a placeholder
// for a missing animation type instead of panicking. Set by engine configuration.
var UsePlaceholderSpriteImages bool

// Sprite represents a game sprite with animations.
type Sprite struct {
	Animations map[AnimationType]*Animation
	Type       SpriteType

	// SourceTileSize is the tile size this sprite's art was drawn for. Zero
	// means it was drawn for whatever the game's tile size is, so no correction
	// applies. It is authorial metadata and is never inferred from the image: a
	// 64 pixel image drawn for 128 pixel tiles and a 64 pixel image drawn for 32
	// pixel tiles are different sprites that happen to share a file size.
	SourceTileSize float64

	// cachedVisibleTopAboveZero caches VisibleTopAboveZero per animation, holding
	// the pre-ratio value so a tile size changed later still takes effect.
	cachedVisibleTopAboveZero map[AnimationType]float64

	// cachedVisibleBounds caches VisibleBounds per animation.
	cachedVisibleBounds map[AnimationType]image.Rectangle
}

// Animation represents a sequence of frames forming an animation.
type Animation struct {
	// Frames are the animation's images in order, each with where it sits in
	// the animation's frame space.
	Frames []Frame

	// Duration is how long one pass through all the frames takes.
	Duration time.Duration

	// ZeroPosition is this animation's anchor: the pixel that sits on the drawn
	// world position, in frame space. Frame space is the coordinate system of
	// one uncropped frame, such as the sheet cell a frame was cut from. Frames of
	// different animations need not share a size or an anchor.
	ZeroPosition geometry.Vector2
}

// Frame is one image of an animation and where that image sits in the
// animation's frame space. Cropping a frame to its content moves its image's
// top-left corner away from frame space's origin, and Offset records by how
// much, so the animation keeps a single anchor however each frame was cropped.
type Frame struct {
	// Image is the frame's pixels.
	Image *ebiten.Image

	// Offset is where Image's top-left pixel sits in frame space: zero for an
	// uncropped frame, the crop box's corner for a cropped one. The anchor in
	// Image's own pixels is the animation's ZeroPosition minus Offset.
	Offset image.Point
}

// FrameAt returns the frame shown once elapsed has passed since the animation
// started, looping. The frames split Duration evenly; a zero Duration holds
// the first frame. It panics on an animation with no frames.
func (a *Animation) FrameAt(elapsed time.Duration) Frame {
	index := 0
	if a.Duration > 0 {
		index = int(elapsed / (a.Duration / time.Duration(len(a.Frames))))
		index %= len(a.Frames)
	}
	return a.Frames[index]
}

// NewSprite creates and returns a new Sprite with default values.
func NewSprite() *Sprite {
	return &Sprite{
		Animations:                make(map[AnimationType]*Animation),
		cachedVisibleTopAboveZero: make(map[AnimationType]float64),
		cachedVisibleBounds:       make(map[AnimationType]image.Rectangle),
	}
}

// AddImage adds an uncropped frame, at offset zero, to the specified animation
// type.
func (s *Sprite) AddImage(animationType AnimationType, img *ebiten.Image) {
	if _, ok := s.Animations[animationType]; !ok {
		s.Animations[animationType] = &Animation{}
	}
	s.Animations[animationType].Frames = append(s.Animations[animationType].Frames, Frame{Image: img})
}

// Image returns the first image of the specified animation type.
// It panics if the animation type does not exist or has no images, unless
// UsePlaceholderSpriteImages is set, in which case it returns nil.
func (s *Sprite) Image(animationType AnimationType) *ebiten.Image {
	if _, ok := s.Animations[animationType]; !ok || len(s.Animations[animationType].Frames) == 0 {
		if !UsePlaceholderSpriteImages {
			panic(fmt.Sprintf("no such animation type: %s", animationType))
		}
		// TODO: return a default image
		return nil
	}
	return s.Animations[animationType].Frames[0].Image
}

// HasAnimation checks if the sprite has a specific animation defined.
func (s *Sprite) HasAnimation(a AnimationType) bool {
	_, ok := s.Animations[a]
	return ok
}

// CanAnimate checks if the sprite can perform a specific animation, either directly or by flipping an existing animation.
func (s *Sprite) CanAnimate(a AnimationType) bool {
	if s.HasAnimation(a) {
		return true
	}
	other, canGenerate := MirroredAnimations[a]
	return canGenerate && s.HasAnimation(other)
}

// AllAnimations returns a slice of all animation types the sprite can draw.
func (s *Sprite) AllAnimations() []AnimationType {
	animations := make([]AnimationType, 0)
	for a := range s.Animations {
		animations = append(animations, a)
	}
	// Add animations that can be generated by flipping (and are not already present)
	for a, other := range MirroredAnimations {
		if !s.HasAnimation(a) && s.HasAnimation(other) {
			animations = append(animations, a)
		}
	}
	return animations
}

// Draw draws the sprite at the given position with the specified animation type.
func (s *Sprite) Draw(screen *ebiten.Image, c *Camera, p geometry.Vector2, a AnimationType) {
	animation, requiresFlip := s.resolveAnimation(a)
	if animation == nil || len(animation.Frames) == 0 {
		if !UsePlaceholderSpriteImages {
			panic(fmt.Sprintf("no such animation type: %s", a))
		}
		return
	}
	frame := animation.Frames[0]
	if frame.Image == nil {
		return
	}
	screen.DrawImage(frame.Image, s.buildDrawOp(p, a, frame.Offset, requiresFlip, c, 1.0))
}

// buildDrawOp builds the draw options for one frame of the sprite at
// world-tile position p: the tile ratio combined with displayScale, the
// frame's anchor offset, an optional horizontal flip, then the camera
// transform. The frame's anchor is the animation's anchor less the frame's
// offset in frame space.
//
// The scale and the anchor offset use the same factor, so the transform is a
// uniform scale about the anchor: the pixel anchored at the world position p
// stays at p, and only the drawn extent changes. A displayScale of 1 draws the
// sprite at the size the game draws it.
func (s *Sprite) buildDrawOp(p geometry.Vector2, a AnimationType, offset image.Point, requiresFlip bool, c *Camera, displayScale float64) *ebiten.DrawImageOptions {
	op := &ebiten.DrawImageOptions{}
	op.Filter = SpriteFilter
	scale := s.TileRatio() * displayScale
	op.GeoM.Scale(scale, scale)
	anchor := s.Anchor(a).Sub(geometry.NewVector2(offset.X, offset.Y))
	op.GeoM.Translate(-anchor.X()*scale, -anchor.Y()*scale)
	if requiresFlip {
		op.GeoM.Scale(-1, 1)
	}
	c.Adjust(op, p)
	return op
}

// DrawAnimation draws the sprite at the given position with the specified animation type.
func (s *Sprite) DrawAnimation(screen *ebiten.Image, c *Camera, p geometry.Vector2, a AnimationType, duration time.Duration) {
	s.DrawAnimationScaled(screen, c, p, a, duration, 1.0)
}

// DrawAnimationScaled is DrawAnimation with an extra per-draw display scale,
// for views that need a sprite drawn smaller or larger than the game draws it
// without mutating the sprite.
//
// The scale is uniform about the sprite's zero position, so the anchor point
// stays on p at any display scale and only the drawn extent changes. A
// displayScale of 1 is identical to DrawAnimation.
func (s *Sprite) DrawAnimationScaled(screen *ebiten.Image, c *Camera, p geometry.Vector2, a AnimationType, duration time.Duration, displayScale float64) {
	animation, requiresFlip := s.resolveAnimation(a)
	if animation == nil {
		panic(fmt.Sprintf("no such animation type: %s", a))
	}
	if len(animation.Frames) == 0 {
		panic(fmt.Sprintf("no image for this animation type: %s", a))
	}

	frame := animation.FrameAt(duration)
	if frame.Image == nil {
		return
	}
	screen.DrawImage(frame.Image, s.buildDrawOp(p, a, frame.Offset, requiresFlip, c, displayScale))
}

// VisibleBounds returns the bounding rectangle of non-transparent pixels in
// the first frame of the given animation, expressed in frame space, the same
// coordinates as Anchor, so a hit test combines the two directly. Cached per
// animation after first call. Returns an empty
// rectangle if no visible content is found.
//
// The rectangle is in the source animation's own coordinates and is not
// mirrored, so a hit test against a flipped sprite is reflected about the
// anchor.
func (s *Sprite) VisibleBounds(a AnimationType) image.Rectangle {
	if cached, ok := s.cachedVisibleBounds[a]; ok {
		return cached
	}
	frame, ok := s.firstFrame(a)
	var result image.Rectangle
	if ok && frame.Image != nil {
		img := frame.Image
		bounds := img.Bounds()
		minX, minY := bounds.Max.X, bounds.Max.Y
		maxX, maxY := bounds.Min.X-1, bounds.Min.Y-1
		for y := bounds.Min.Y; y < bounds.Max.Y; y++ {
			for x := bounds.Min.X; x < bounds.Max.X; x++ {
				_, _, _, alpha := img.At(x, y).RGBA()
				if alpha == 0 {
					continue
				}
				if x < minX {
					minX = x
				}
				if x > maxX {
					maxX = x
				}
				if y < minY {
					minY = y
				}
				if y > maxY {
					maxY = y
				}
			}
		}
		if maxX >= minX && maxY >= minY {
			// Normalize to the frame's own origin, then place it in frame space.
			result = image.Rect(
				minX-bounds.Min.X, minY-bounds.Min.Y,
				maxX-bounds.Min.X+1, maxY-bounds.Min.Y+1,
			).Add(frame.Offset)
		}
	}
	s.cachedVisibleBounds[a] = result
	return result
}

// VisibleTopAboveZero returns how far the visible sprite content
// (non-transparent pixels) extends above ZeroPosition, measured for the given
// animation, since animations may have different crop sizes and anchors,
// measured in drawn pixels including the tile ratio: the row offset and
// ZeroPosition are both in source pixels, and the tile ratio maps them to
// what ends up on screen. The result is cached per animation; the cache holds
// the pre-ratio value, so the ratio is applied fresh on every call and a tile
// size changed after the first call still takes effect.
//
// Use this instead of the raw frame height when placing UI elements (like
// nameplates) above a sprite: transparent padding at the top of the frame is
// not counted, and the result maps to screen pixels by a single multiply with
// the camera's effective zoom.
//
// The result describes a draw at a display scale of 1, which is what
// DrawAnimation uses. DrawAnimationScaled scales uniformly about the zero
// position, so a caller placing UI above a sprite drawn at a display scale
// multiplies this result by that same scale.
func (s *Sprite) VisibleTopAboveZero(a AnimationType) float64 {
	if cached, ok := s.cachedVisibleTopAboveZero[a]; ok {
		return cached * s.TileRatio()
	}

	frame, ok := s.firstFrame(a)
	result := 0.0
	if ok && frame.Image != nil {
		img := frame.Image
		// The anchor in this frame's own pixels, which is what the row index
		// below is measured in.
		anchorY := s.Anchor(a).Y() - float64(frame.Offset.Y)
		bounds := img.Bounds()
		for y := bounds.Min.Y; y < bounds.Max.Y; y++ {
			rowHasPixel := false
			for x := bounds.Min.X; x < bounds.Max.X; x++ {
				_, _, _, alpha := img.At(x, y).RGBA()
				if alpha > 0 {
					rowHasPixel = true
					break
				}
			}
			if rowHasPixel {
				// (y - bounds.Min.Y) is the row index within the frame. Both it
				// and anchorY are in the frame's own source pixels, so the first
				// visible pixel sits anchorY - rowIndex source pixels above the
				// anchor.
				result = anchorY - float64(y-bounds.Min.Y)
				break
			}
		}
	}

	s.cachedVisibleTopAboveZero[a] = result
	return result * s.TileRatio()
}

// SetSourceTileSize sets the tile size this sprite's art was drawn for and
// returns the sprite, so it chains with the other setters.
func (s *Sprite) SetSourceTileSize(size float64) *Sprite {
	s.SourceTileSize = size
	return s
}

// TileRatio is the scale that maps art drawn for SourceTileSize onto the game's
// current TileSize, and 1 for a sprite that declares no SourceTileSize. It is
// computed on every call rather than stored, because sprites are built from
// init() before settings are applied.
//
// The engine already applies it at draw time, so a caller that only draws
// sprites never needs it. Use it when reconstructing a sprite's drawn size or
// position outside the draw path: fitting art into a fixed slot, hit-testing a
// sprite's screen rectangle, or placing UI against its extent. Multiplying a
// frame's raw pixel size by this ratio gives the size the engine draws it at.
func (s *Sprite) TileRatio() float64 {
	if s.SourceTileSize <= 0 {
		return 1.0
	}
	return TileSize / s.SourceTileSize
}

// Anchor returns the anchor of the given animation, resolving a mirrored
// animation to the animation it is drawn from, since those are the frames that
// end up on screen. An animation the sprite does not have returns the zero
// vector: this is a query, not a draw.
func (s *Sprite) Anchor(a AnimationType) geometry.Vector2 {
	animation, _ := s.resolveAnimation(a)
	if animation == nil {
		return geometry.Zero2D()
	}
	return animation.ZeroPosition
}

// resolveAnimation returns the animation that a is drawn from and whether
// drawing it needs a horizontal flip: a itself when the sprite has it,
// otherwise its mirror from MirroredAnimations. It returns nil when neither
// exists.
func (s *Sprite) resolveAnimation(a AnimationType) (*Animation, bool) {
	if animation, ok := s.Animations[a]; ok {
		return animation, false
	}
	if other, mirrored := MirroredAnimations[a]; mirrored {
		if animation, ok := s.Animations[other]; ok {
			return animation, true
		}
	}
	return nil, false
}

// firstFrame returns the first frame of a, resolving a mirrored animation to
// the animation it is drawn from, and false when neither exists or has frames.
func (s *Sprite) firstFrame(a AnimationType) (Frame, bool) {
	animation, _ := s.resolveAnimation(a)
	if animation == nil || len(animation.Frames) == 0 {
		return Frame{}, false
	}
	return animation.Frames[0], true
}

// SetZeroPosition sets one anchor on every animation the sprite currently has,
// which is the right thing for a uniform sheet where every frame shares an
// anchor. Animations added afterwards do not get it, so it panics on a sprite
// with no animations: that call is misordered rather than merely early.
func (s *Sprite) SetZeroPosition(pos geometry.Vector2) *Sprite {
	if len(s.Animations) == 0 {
		panic("SetZeroPosition on a sprite with no animations: add frames first")
	}
	for _, animation := range s.Animations {
		animation.ZeroPosition = pos
	}
	return s
}

// SetType sets the type of the sprite.
func (s *Sprite) SetType(spriteType SpriteType) *Sprite {
	s.Type = spriteType
	return s
}

// MirroredAnimations maps a left-facing animation to the right-facing animation
// it is rendered from by a horizontal flip, so left variants need not be
// authored separately.
var (
	MirroredAnimations = map[AnimationType]AnimationType{
		AnimationIdleLeft:   AnimationIdleRight,
		AnimationMoveLeft:   AnimationMoveRight,
		AnimationAttackLeft: AnimationAttackRight,
	}
)

// AnimationSpec describes one animation's geometry within an image: where its
// frames are, where each sits in frame space, where the anchor is, and how
// long it runs. It is the load-time description of an animation, where
// Animation is the loaded form; the two differ in that a spec names frames as
// rectangles into a source image while an Animation holds uploaded textures.
//
// Frames need not be the same size as each other or as another animation's,
// which is what lets a sheet be packed with one crop box per frame.
type AnimationSpec struct {
	// Frames are this animation's frames, in order.
	Frames []FrameSpec

	// Anchor is the pixel that sits on the drawn world position, in frame
	// space.
	Anchor geometry.Vector2

	// Duration is how long the whole animation runs. Zero means one second.
	Duration time.Duration
}

// FrameSpec is one frame of an AnimationSpec: its source rectangle and where
// that rectangle's top-left sits in frame space.
type FrameSpec struct {
	// Rect is the frame's source rectangle in the image.
	Rect image.Rectangle

	// Offset is where Rect's top-left pixel sits in frame space, zero for an
	// uncropped frame.
	Offset image.Point
}

// sortedAnimationTypes returns m's keys in ascending order, so anything built
// from a map of animations is reproducible rather than depending on Go's map
// iteration order.
func sortedAnimationTypes[V any](m map[AnimationType]V) []AnimationType {
	types := make([]AnimationType, 0, len(m))
	for a := range m {
		types = append(types, a)
	}
	slices.Sort(types)
	return types
}

// LoadSpriteAnimations builds a sprite whose animations each carry their own
// frame rectangles and offsets, anchor and duration. Frames are sub-images of img, so the
// whole sprite costs one texture however many animations it has.
//
// Use it when a sheet is not a uniform grid, or when animations need different
// anchors. LoadSprite is the convenience for the uniform case and is built on
// this.
func LoadSpriteAnimations(img *ebiten.Image, specs map[AnimationType]AnimationSpec) (*Sprite, error) {
	sprite := NewSprite()
	bounds := img.Bounds()

	for _, a := range sortedAnimationTypes(specs) {
		spec := specs[a]
		if len(spec.Frames) == 0 {
			return nil, fmt.Errorf("animation %s: no frames", a)
		}
		frames := make([]Frame, 0, len(spec.Frames))
		for i, f := range spec.Frames {
			if f.Rect.Empty() {
				return nil, fmt.Errorf("animation %s frame %d: empty rectangle %v", a, i, f.Rect)
			}
			if !f.Rect.In(bounds) {
				return nil, fmt.Errorf("animation %s frame %d: rectangle %v is outside the image bounds %v", a, i, f.Rect, bounds)
			}
			frames = append(frames, Frame{Image: img.SubImage(f.Rect).(*ebiten.Image), Offset: f.Offset})
		}

		duration := spec.Duration
		if duration == 0 {
			duration = time.Second
		}
		sprite.Animations[a] = &Animation{Frames: frames, Duration: duration, ZeroPosition: spec.Anchor}
	}

	return sprite, nil
}

// MustLoadSpriteAnimations is like LoadSpriteAnimations but panics on error.
func MustLoadSpriteAnimations(img *ebiten.Image, specs map[AnimationType]AnimationSpec) *Sprite {
	sprite, err := LoadSpriteAnimations(img, specs)
	if err != nil {
		panic(fmt.Sprintf("loading sprite animations: %v", err))
	}
	return sprite
}

// LoadSprite slices img into a grid of width columns by height rows, assigns the
// frame indexes in indexes to each AnimationType, and sets per-animation
// durations (defaulting to one second when unspecified). Note: width and height
// are column/row counts, not pixel dimensions.
//
// It is the convenience for a uniform sheet, expressed on top of
// LoadSpriteAnimations. Anchors are left at zero, since a uniform sheet's anchor
// is normally set once for the whole sprite with SetZeroPosition.
func LoadSprite(img *ebiten.Image, width, height int, indexes map[AnimationType][]int, durations map[AnimationType]time.Duration) (*Sprite, error) {
	w, h := img.Bounds().Dx(), img.Bounds().Dy()
	tileWidth := w / width
	tileHeight := h / height

	specs := make(map[AnimationType]AnimationSpec, len(indexes))
	for animationType, animationIndexes := range indexes {
		// An empty index list creates no animation at all, so it must not reach
		// LoadSpriteAnimations, which rejects a spec with no frames.
		if len(animationIndexes) == 0 {
			continue
		}
		frames := make([]FrameSpec, 0, len(animationIndexes))
		for _, index := range animationIndexes {
			x := (index % width) * tileWidth
			y := (index / width) * tileHeight
			frames = append(frames, FrameSpec{Rect: image.Rect(x, y, x+tileWidth, y+tileHeight)})
		}
		specs[animationType] = AnimationSpec{Frames: frames, Duration: durations[animationType]}
	}

	return LoadSpriteAnimations(img, specs)
}

// MustLoadSprite is like LoadSprite but panics on error.
func MustLoadSprite(img *ebiten.Image, width, height int, indexes map[AnimationType][]int, durations map[AnimationType]time.Duration) *Sprite {
	sprite, err := LoadSprite(img, width, height, indexes, durations)
	if err != nil {
		panic(fmt.Sprintf("loading sprite: %v", err))
	}
	return sprite
}
