package render

import (
	"fmt"
	"image"
	"time"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/trancecode/vantage/geometry"
)

// UsePlaceholderSpriteImages, when true, makes Sprite.Image return a placeholder
// for a missing animation type instead of panicking. Set by engine configuration.
var UsePlaceholderSpriteImages bool

// Sprite represents a game sprite with animations.
type Sprite struct {
	Animations   map[AnimationType]*Animation
	ZeroPosition geometry.Vector2
	Scale        float64
	Type         SpriteType

	// cachedVisibleTopAboveZero caches the result of VisibleTopAboveZero.
	cachedVisibleTopAboveZero *float64

	// cachedVisibleBounds caches the result of VisibleBounds.
	cachedVisibleBounds *image.Rectangle
}

// Animation represents a sequence of images forming an animation.
type Animation struct {
	Images   []*ebiten.Image
	Duration time.Duration
}

// NewSprite creates and returns a new Sprite with default values.
func NewSprite() *Sprite {
	return &Sprite{
		Animations:   make(map[AnimationType]*Animation),
		ZeroPosition: geometry.NewVector2(0, 0),
		Scale:        1.0,
	}
}

// AddImage adds an image to the specified animation type.
func (s *Sprite) AddImage(animationType AnimationType, img *ebiten.Image) {
	if _, ok := s.Animations[animationType]; !ok {
		s.Animations[animationType] = &Animation{
			Images: []*ebiten.Image{},
		}
	}
	s.Animations[animationType].Images = append(s.Animations[animationType].Images, img)
}

// Image returns the first image of the specified animation type.
// It logs a fatal error if the animation type does not exist.
func (s *Sprite) Image(animationType AnimationType) *ebiten.Image {
	if _, ok := s.Animations[animationType]; !ok || len(s.Animations[animationType].Images) == 0 {
		if !UsePlaceholderSpriteImages {
			panic(fmt.Sprintf("no such animation type: %s", animationType))
		}
		// TODO: return a default image
		return nil
	}
	return s.Animations[animationType].Images[0]
}

// HasAnimation checks if the sprite has a specific animation defined.
func (s *Sprite) HasAnimation(a AnimationType) bool {
	_, ok := s.Animations[a]
	return ok
}

// CanAnimate checks if the sprite can perform a specific animation, either directly or by flipping an existing animation.
func (s *Sprite) CanAnimate(a AnimationType) bool {
	if s.HasAnimation(a) {
		return true
	}
	other, canGenerate := AnimationsToGenerate[a]
	return canGenerate && s.HasAnimation(other)
}

// AllAnimations returns a slice of all animation types the sprite can draw.
func (s *Sprite) AllAnimations() []AnimationType {
	animations := make([]AnimationType, 0)
	for a := range s.Animations {
		animations = append(animations, a)
	}
	// Add animations that can be generated by flipping (and are not already present)
	for a, other := range AnimationsToGenerate {
		if !s.HasAnimation(a) && s.HasAnimation(other) {
			animations = append(animations, a)
		}
	}
	return animations
}

// Draw draws the sprite at the given position with the specified animation type.
func (s *Sprite) Draw(p geometry.Vector2, a AnimationType, screen *ebiten.Image, c *Camera) {
	var img *ebiten.Image

	op := &ebiten.DrawImageOptions{}

	// Apply sprite's scale
	op.GeoM.Scale(s.Scale, s.Scale)

	// Apply sprite's zero position offset
	op.GeoM.Translate(-s.ZeroPosition.X(), -s.ZeroPosition.Y())

	// Check if we need to flip horizontally
	if _, ok := s.Animations[a]; !ok {
		if existingAnimationType, shouldFlip := AnimationsToGenerate[a]; shouldFlip {
			img = s.Image(existingAnimationType)
			if _, ok := s.Animations[existingAnimationType]; ok {
				op.GeoM.Scale(-1, 1)
			}
		}
	}

	// Adjust for the camera position and zoom
	c.Adjust(op, p)

	if img == nil {
		img = s.Image(a)
	}
	if img == nil {
		return
	}
	screen.DrawImage(img, op)
}

// DrawAnimation draws the sprite at the given position with the specified animation type.
func (s *Sprite) DrawAnimation(p geometry.Vector2, a AnimationType, duration time.Duration, screen *ebiten.Image, c *Camera) {
	var requiresFlip bool
	animation, animationExists := s.Animations[a]

	if !animationExists {
		// Check if we need to flip horizontally
		if existingAnimationType, shouldFlip := AnimationsToGenerate[a]; shouldFlip {
			requiresFlip = true
			animation = s.Animations[existingAnimationType]
		} else {
			panic(fmt.Sprintf("no such animation type: %s", a))
		}
	}

	if len(animation.Images) == 0 {
		panic(fmt.Sprintf("no image for this animation type: %s", a))
	}

	// Determine which frame to draw based on the duration and animation speed
	frameIndex := 0
	if animation.Duration > 0 {
		frameIndex = int(duration / (animation.Duration / time.Duration(len(animation.Images))))
		frameIndex %= len(animation.Images) // Loop the animation
	}

	img := animation.Images[frameIndex]

	op := &ebiten.DrawImageOptions{}

	// Apply sprite's scale
	op.GeoM.Scale(s.Scale, s.Scale)

	// Apply sprite's zero position offset
	op.GeoM.Translate(-s.ZeroPosition.X(), -s.ZeroPosition.Y())

	// Check if we need to flip horizontally
	if requiresFlip {
		op.GeoM.Scale(-1, 1)
	}

	// Adjust for the camera position and zoom
	c.Adjust(op, p)

	if img == nil {
		return
	}
	screen.DrawImage(img, op)
}

// VisibleBounds returns the bounding rectangle of non-transparent pixels in
// one frame, expressed in frame-local pixel coordinates. Cached after first
// call. Returns an empty rectangle if no visible content is found.
func (s *Sprite) VisibleBounds() image.Rectangle {
	if s.cachedVisibleBounds != nil {
		return *s.cachedVisibleBounds
	}
	var img *ebiten.Image
	for _, anim := range s.Animations {
		if len(anim.Images) > 0 {
			img = anim.Images[0]
			break
		}
	}
	var result image.Rectangle
	if img != nil {
		frame := img.Bounds()
		minX, minY := frame.Max.X, frame.Max.Y
		maxX, maxY := frame.Min.X-1, frame.Min.Y-1
		for y := frame.Min.Y; y < frame.Max.Y; y++ {
			for x := frame.Min.X; x < frame.Max.X; x++ {
				_, _, _, a := img.At(x, y).RGBA()
				if a == 0 {
					continue
				}
				if x < minX {
					minX = x
				}
				if x > maxX {
					maxX = x
				}
				if y < minY {
					minY = y
				}
				if y > maxY {
					maxY = y
				}
			}
		}
		if maxX >= minX && maxY >= minY {
			// Normalize to frame-local (0,0) origin.
			result = image.Rect(
				minX-frame.Min.X, minY-frame.Min.Y,
				maxX-frame.Min.X+1, maxY-frame.Min.Y+1,
			)
		}
	}
	s.cachedVisibleBounds = &result
	return result
}

// VisibleTopAboveZero returns the number of pixels the visible sprite
// content (non-transparent pixels) extends above ZeroPosition in one frame.
// Frames across animations share the same size and layout, so the result is
// computed once from any available frame and cached.
//
// Use this instead of the raw frame height when placing UI elements (like
// nameplates) above a sprite, so transparent padding at the top of the frame
// is not counted as part of the visible sprite.
func (s *Sprite) VisibleTopAboveZero() float64 {
	if s.cachedVisibleTopAboveZero != nil {
		return *s.cachedVisibleTopAboveZero
	}

	var img *ebiten.Image
	for _, anim := range s.Animations {
		if len(anim.Images) > 0 {
			img = anim.Images[0]
			break
		}
	}
	result := 0.0
	if img != nil {
		bounds := img.Bounds()
		for y := bounds.Min.Y; y < bounds.Max.Y; y++ {
			rowHasPixel := false
			for x := bounds.Min.X; x < bounds.Max.X; x++ {
				_, _, _, a := img.At(x, y).RGBA()
				if a > 0 {
					rowHasPixel = true
					break
				}
			}
			if rowHasPixel {
				// (y - bounds.Min.Y) is the row index within the frame.
				// ZeroPosition.Y() - rowIndex is how far above ZeroPosition
				// the first visible pixel sits.
				result = s.ZeroPosition.Y() - float64(y-bounds.Min.Y)
				break
			}
		}
	}

	s.cachedVisibleTopAboveZero = &result
	return result
}

// SetScale sets the scale of the sprite.
func (s *Sprite) SetScale(scale float64) *Sprite {
	s.Scale = scale
	return s
}

// SetZeroPosition sets the zero position of the sprite.
func (s *Sprite) SetZeroPosition(pos geometry.Vector2) *Sprite {
	s.ZeroPosition = pos
	return s
}

// SetType sets the type of the sprite.
func (s *Sprite) SetType(spriteType SpriteType) *Sprite {
	s.Type = spriteType
	return s
}

var (
	AnimationsToGenerate = map[AnimationType]AnimationType{
		AnimationIdleLeft:   AnimationIdleRight,
		AnimationMoveLeft:   AnimationMoveRight,
		AnimationAttackLeft: AnimationAttackRight,
	}
)

func LoadSprite(img *ebiten.Image, width, height int, indexes map[AnimationType][]int, durations map[AnimationType]time.Duration) (*Sprite, error) {
	sprite := NewSprite()
	// Get the size of each tile
	w, h := img.Bounds().Dx(), img.Bounds().Dy()
	tileWidth := w / width
	tileHeight := h / height

	for animationType, animationIndexes := range indexes {
		for _, index := range animationIndexes {
			// Calculate the position of the tile in the sprite sheet
			x := (index % width) * tileWidth
			y := (index / width) * tileHeight

			// Create a sub-image of the tile
			rect := image.Rect(x, y, x+tileWidth, y+tileHeight)
			subImg := img.SubImage(rect).(*ebiten.Image)

			// Add the tile to the animation
			sprite.AddImage(animationType, subImg)
		}

		// Set the animation duration if it exists
		duration, ok := durations[animationType]
		if !ok {
			duration = time.Second
		}
		sprite.Animations[animationType].Duration = duration
	}

	return sprite, nil
}

func MustLoadSprite(img *ebiten.Image, width, height int, indexes map[AnimationType][]int, durations map[AnimationType]time.Duration) *Sprite {
	sprite, err := LoadSprite(img, width, height, indexes, durations)
	if err != nil {
		panic(fmt.Sprintf("loading sprite: %v", err))
	}
	return sprite
}
