name: Commit Message Validation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  validate:
    uses: trancecode/github-workflows/.github/workflows/commit-validation.yml@main
