name: Go

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'docs/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libc6-dev libgl1-mesa-dev libxcursor-dev libxi-dev \
            libxinerama-dev libxrandr-dev libxxf86vm-dev \
            libasound2-dev pkg-config xorg-dev xvfb

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.4'
          cache: true

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...
        env:
          GOFLAGS: "-buildvcs=false"

      - name: Test
        env:
          CI: true
        run: xvfb-run -a go test -v ./...
